version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config:/prometheus
      - ./data/prometheus:/data
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
    ports:
      - 9090:9090
    depends_on:
      - infracloud
    restart: always
    networks:
      - promnet

  infracloud:
    image: infracloudio/csvserver
    networks:
    - promnet
    ports:
    - 9393:9300
    environment:
      CSVSERVER_BORDER: Orange
    volumes:
    - ./inputFile:/csvserver/inputdata

networks:
  promnet:
    driver: bridge
